// DoS region dictionaries
var Africa = {
  'Angola': 'AGO',
  'Benin': 'BEN',
  'Botswana': 'BWA',
  'Burkina Faso': 'BFA',
  'Burundi': 'BDI',
  'Cabo Verde': 'CPV',
  'Cameroon': 'CMR',
  'Central African Republic': 'CAF',
  'Chad': 'TCD',
  'Comoros': 'COM',
  'Côte d’Ivoire': 'CIV',
  'Democratic Republic of the Congo': 'COD',
  'Djibouti': 'DJI',
  'Equatorial Guinea': 'GNQ',
  'Eritrea': 'ERI',
  'Eswatini': 'SWZ',
  'Ethiopia': 'ETH',
  'Gabon': 'GAB',
  'Gambia': 'GMB',
  'Ghana': 'GHA',
  'Guinea': 'GIN',
  'Guinea-Bissau': 'GNB',
  'Kenya': 'KEN',
  'Lesotho': 'LSO',
  'Liberia': 'LBR',
  'Madagascar': 'MDG',
  'Malawi': 'MWI',
  'Mali': 'MLI',
  'Mauritania': 'MRT',
  'Mauritius': 'MUS',
  'Mozambique': 'MOZ',
  'Namibia': 'NAM',
  'Niger': 'NER',
  'Nigeria': 'NGA',
  'Republic of the Congo': 'COG',
  'Rwanda': 'RWA',
  'São Tomé and Príncipe': 'STP',
  'Senegal': 'SEN',
  'Seychelles': 'SYC',
  'Sierra Leone': 'SLE',
  'Somalia': 'SOM',
  'South Africa': 'ZAF',
  'South Sudan': 'SSD',
  'Sudan': 'SDN',
  'Tanzania': 'TZA',
  'Togo': 'TGO',
  'Uganda': 'UGA',
  'Zambia': 'ZMB',
  'Zimbabwe': 'ZWE'
};
var EastAsiaAndPacific = {};
var EuropeAndEurasia = {};
var NearEast = {};
var SouthAndCentralAsia = {};
var WesternHemisphere = {};
