// find iso 3 by DoS region
var Africa = {
  "Angola": "AGO",
  "Benin": "BEN",
  "Botswana": "BWA",
  "Burkina Faso": "BFA",
  "Burundi": "BDI",
  "Cabo Verde": "CPV",
  "Cameroon": "CMR",
  "Central African Republic": "CAF",
  "Chad": "TCD",
  "Comoros": "COM",
  "Côte d’Ivoire": "CIV",
  "Democratic Republic of the Congo": "COD",
  "Djibouti": "DJI",
  "Equatorial Guinea": "GNQ",
  "Eritrea": "ERI",
  "Eswatini": "SWZ",
  "Ethiopia": "ETH",
  "Gabon": "GAB",
  "Gambia": "GMB",
  "Ghana": "GHA",
  "Guinea": "GIN",
  "Guinea-Bissau": "GNB",
  "Kenya": "KEN",
  "Lesotho": "LSO",
  "Liberia": "LBR",
  "Madagascar": "MDG",
  "Malawi": "MWI",
  "Mali": "MLI",
  "Mauritania": "MRT",
  "Mauritius": "MUS",
  "Mozambique": "MOZ",
  "Namibia": "NAM",
  "Niger": "NER",
  "Nigeria": "NGA",
  "Republic of the Congo": "COG",
  "Rwanda": "RWA",
  "São Tomé and Príncipe": "STP",
  "Senegal": "SEN",
  "Seychelles": "SYC",
  "Sierra Leone": "SLE",
  "Somalia": "SOM",
  "South Africa": "ZAF",
  "South Sudan": "SSD",
  "Sudan": "SDN",
  "Tanzania": "TZA",
  "Togo": "TGO",
  "Uganda": "UGA",
  "Zambia": "ZMB",
  "Zimbabwe": "ZWE"
};
var EastAsiaAndPacific = {
  "Australia": "AUS",
  "Brunei": "BRN",
  "Burma": "MMR",
  "Cambodia": "KHM",
  "China": "CHN",
  "Fiji": "FJI",
  "Indonesia": "IDN",
  "Japan": "JPN",
  "Kiribati": "KIR",
  "Laos": "LAO",
  "Malaysia": "MYS",
  "Marshall Islands": "MHL",
  "Micronesia": "FSM",
  "Mongolia": "MNG",
  "Nauru": "NRU",
  "New Zealand": "NZL",
  "North Korea": "PRK",
  "Palau": "PLW",
  "Papua New Guinea": "PNG",
  "Philippines": "PHL",
  "Samoa": "WSM",
  "Singapore": "SGP",
  "Solomon Islands": "SLB",
  "South Korea": "KOR",
  "Taiwan": "TWN",
  "Thailand": "THA",
  "Timor-Leste": "TLS",
  "Tonga": "TON",
  "Tuvalu": "TUV",
  "Vanuatu": "VUT",
  "Vietnam": "VNM"
};
var EuropeAndEurasia = {
  "Albania": "ALB",
  "Andorra": "AND",
  "Armenia": "ARM",
  "Austria": "AUT",
  "Azerbaijan": "AZE",
  "Belarus": "BLR",
  "Belgium": "BEL",
  "Bosnia and Herzegovina": "BIH",
  "Bulgaria": "BGR",
  "Croatia": "HRV",
  "Cyprus": "CYP",
  "Czechia": "CZE",
  "Denmark": "DNK",
  "Estonia": "EST",
  "Finland": "FIN",
  "France": "FRA",
  "Georgia": "GEO",
  "Germany": "DEU",
  "Greece": "GRC",
  "Greenland": "GRL",
  "Holy See": "VAT",
  "Hungary": "HUN",
  "Iceland": "ISL",
  "Ireland": "IRL",
  "Italy": "ITA",
  "Kosovo": "RKS",
  "Latvia": "LVA",
  "Liechtenstein": "LIE",
  "Lithuania": "LTU",
  "Luxembourg": "LUX",
  "Malta": "MLT",
  "Moldova": "MDA",
  "Monaco": "MCO",
  "Montenegro": "MNE",
  "Netherlands": "NLD",
  "North Macedonia": "MKD",
  "Norway": "NOR",
  "Poland": "POL",
  "Portugal": "PRT",
  "Romania": "ROU",
  "Russia": "RUS",
  "San Marino": "SMR",
  "Serbia": "SRB",
  "Slovakia": "SVK",
  "Slovenia": "SVN",
  "Spain": "ESP",
  "Sweden": "SWE",
  "Switzerland": "CHE",
  "Turkey": "TUR",
  "Ukraine": "UKR",
  "United Kingdom": "GBR"
};
var NearEast = {
  "Algeria": "DZA",
  "Bahrain": "BHR",
  "Egypt": "EGY",
  "Iran": "IRN",
  "Iraq": "IRQ",
  "Israel": "ISR",
  "Jordan": "JOR",
  "Kuwait": "KWT",
  "Lebanon": "LBN",
  "Libya": "LBY",
  "Morocco": "MAR",
  "Oman": "OMN",
  "Palestinian Territories": "PSE",
  "Qatar": "QAT",
  "Saudi Arabia": "SAU",
  "Syria": "SYR",
  "Tunisia": "TUN",
  "United Arab Emirates": "ARE",
  "Yemen": "YEM"
};
var SouthAndCentralAsia = {
  "Afghanistan": "AFG",
  "Bangladesh": "BGD",
  "Bhutan": "BTN",
  "India": "IND",
  "Kazakhstan": "KAZ",
  "Kyrgyzstan": "KGZ",
  "Maldives": "MDV",
  "Nepal": "NPL",
  "Pakistan": "PAK",
  "Sri Lanka": "LKA",
  "Tajikistan": "TJK",
  "Turkmenistan": "TKM",
  "Uzbekistan": "UZB"
};
var WesternHemisphere = {
  "Antigua and Barbuda": "ATG",
  "Argentina": "ARG",
  "Bahamas": "BHS",
  "Barbados": "BRB",
  "Belize": "BLZ",
  "Bolivia": "BOL",
  "Brazil": "BRA",
  "Canada": "CAN",
  "Chile": "CHL",
  "Colombia": "COL",
  "Costa Rica": "CRI",
  "Cuba": "CUB",
  "Dominica": "DMA",
  "Dominican Republic": "DOM",
  "Ecuador": "ECU",
  "El Salvador": "SLV",
  "Grenada": "GRD",
  "Guatemala": "GTM",
  "Guyana": "GUY",
  "Haiti": "HTI",
  "Honduras": "HND",
  "Jamaica": "JAM",
  "Mexico": "MEX",
  "Nicaragua": "NIC",
  "Panama": "PAN",
  "Paraguay": "PRY",
  "Peru": "PER",
  "Saint Kitts and Nevis": "KNA",
  "Saint Lucia": "LCA",
  "Saint Vincent and the Grenadines": "VCT",
  "Suriname": "SUR",
  "Trinadad and Tobago": "TTO",
  "Uruguay": "URY",
  "Venezuela": "VEN"
};

// find DoS region by country
var Countries = {
  "Angola": "Africa",
  "Benin": "Africa",
  "Botswana": "Africa",
  "Burkina Faso": "Africa",
  "Burundi": "Africa",
  "Cabo Verde": "Africa",
  "Cameroon": "Africa",
  "Central African Republic": "Africa",
  "Chad": "Africa",
  "Comoros": "Africa",
  "Côte d’Ivoire": "Africa",
  "Democratic Republic of the Congo": "Africa",
  "Djibouti": "Africa",
  "Equatorial Guinea": "Africa",
  "Eritrea": "Africa",
  "Eswatini": "Africa",
  "Ethiopia": "Africa",
  "Gabon": "Africa",
  "Gambia": "Africa",
  "Ghana": "Africa",
  "Guinea": "Africa",
  "Guinea-Bissau": "Africa",
  "Kenya": "Africa",
  "Lesotho": "Africa",
  "Liberia": "Africa",
  "Madagascar": "Africa",
  "Malawi": "Africa",
  "Mali": "Africa",
  "Mauritania": "Africa",
  "Mauritius": "Africa",
  "Mozambique": "Africa",
  "Namibia": "Africa",
  "Niger": "Africa",
  "Nigeria": "Africa",
  "Republic of the Congo": "Africa",
  "Rwanda": "Africa",
  "São Tomé and Príncipe": "Africa",
  "Senegal": "Africa",
  "Seychelles": "Africa",
  "Sierra Leone": "Africa",
  "Somalia": "Africa",
  "South Africa": "Africa",
  "South Sudan": "Africa",
  "Sudan": "Africa",
  "Tanzania": "Africa",
  "Togo": "Africa",
  "Uganda": "Africa",
  "Zambia": "Africa",
  "Zimbabwe": "Africa",
  "Australia": "East Asia and Pacific",
  "Brunei": "East Asia and Pacific",
  "Burma": "East Asia and Pacific",
  "Cambodia": "East Asia and Pacific",
  "China": "East Asia and Pacific",
  "Fiji": "East Asia and Pacific",
  "Indonesia": "East Asia and Pacific",
  "Japan": "East Asia and Pacific",
  "Kiribati": "East Asia and Pacific",
  "Laos": "East Asia and Pacific",
  "Malaysia": "East Asia and Pacific",
  "Marshall Islands": "East Asia and Pacific",
  "Micronesia": "East Asia and Pacific",
  "Mongolia": "East Asia and Pacific",
  "Nauru": "East Asia and Pacific",
  "New Zealand": "East Asia and Pacific",
  "North Korea": "East Asia and Pacific",
  "Palau": "East Asia and Pacific",
  "Papua New Guinea": "East Asia and Pacific",
  "Philippines": "East Asia and Pacific",
  "Samoa": "East Asia and Pacific",
  "Singapore": "East Asia and Pacific",
  "Solomon Islands": "East Asia and Pacific",
  "South Korea": "East Asia and Pacific",
  "Taiwan": "East Asia and Pacific",
  "Thailand": "East Asia and Pacific",
  "Timor-Leste": "East Asia and Pacific",
  "Tonga": "East Asia and Pacific",
  "Tuvalu": "East Asia and Pacific",
  "Vanuatu": "East Asia and Pacific",
  "Vietnam": "East Asia and Pacific",
  "Albania": "Europe and Eurasia",
  "Andorra": "Europe and Eurasia",
  "Armenia": "Europe and Eurasia",
  "Austria": "Europe and Eurasia",
  "Azerbaijan": "Europe and Eurasia",
  "Belarus": "Europe and Eurasia",
  "Belgium": "Europe and Eurasia",
  "Bosnia and Herzegovina": "Europe and Eurasia",
  "Bulgaria": "Europe and Eurasia",
  "Croatia": "Europe and Eurasia",
  "Cyprus": "Europe and Eurasia",
  "Czechia": "Europe and Eurasia",
  "Denmark": "Europe and Eurasia",
  "Estonia": "Europe and Eurasia",
  "Finland": "Europe and Eurasia",
  "France": "Europe and Eurasia",
  "Georgia": "Europe and Eurasia",
  "Germany": "Europe and Eurasia",
  "Greece": "Europe and Eurasia",
  "Greenland": "Europe and Eurasia",
  "Holy See": "Europe and Eurasia",
  "Hungary": "Europe and Eurasia",
  "Iceland": "Europe and Eurasia",
  "Ireland": "Europe and Eurasia",
  "Italy": "Europe and Eurasia",
  "Kosovo": "Europe and Eurasia",
  "Latvia": "Europe and Eurasia",
  "Liechtenstein": "Europe and Eurasia",
  "Lithuania": "Europe and Eurasia",
  "Luxembourg": "Europe and Eurasia",
  "Malta": "Europe and Eurasia",
  "Moldova": "Europe and Eurasia",
  "Monaco": "Europe and Eurasia",
  "Montenegro": "Europe and Eurasia",
  "Netherlands": "Europe and Eurasia",
  "North Macedonia": "Europe and Eurasia",
  "Norway": "Europe and Eurasia",
  "Poland": "Europe and Eurasia",
  "Portugal": "Europe and Eurasia",
  "Romania": "Europe and Eurasia",
  "Russia": "Europe and Eurasia",
  "San Marino": "Europe and Eurasia",
  "Serbia": "Europe and Eurasia",
  "Slovakia": "Europe and Eurasia",
  "Slovenia": "Europe and Eurasia",
  "Spain": "Europe and Eurasia",
  "Sweden": "Europe and Eurasia",
  "Switzerland": "Europe and Eurasia",
  "Turkey": "Europe and Eurasia",
  "Ukraine": "Europe and Eurasia",
  "United Kingdom": "Europe and Eurasia",
  "Algeria": "Near East",
  "Bahrain": "Near East",
  "Egypt": "Near East",
  "Iran": "Near East",
  "Iraq": "Near East",
  "Israel": "Near East",
  "Jordan": "Near East",
  "Kuwait": "Near East",
  "Lebanon": "Near East",
  "Libya": "Near East",
  "Morocco": "Near East",
  "Oman": "Near East",
  "Palestinian Territories": "Near East",
  "Qatar": "Near East",
  "Saudi Arabia": "Near East",
  "Syria": "Near East",
  "Tunisia": "Near East",
  "United Arab Emirates": "Near East",
  "Yemen": "Near East",
  "Afghanistan": "South and Central Asia",
  "Bangladesh": "South and Central Asia",
  "Bhutan": "South and Central Asia",
  "India": "South and Central Asia",
  "Kazakhstan": "South and Central Asia",
  "Kyrgyzstan": "South and Central Asia",
  "Maldives": "South and Central Asia",
  "Nepal": "South and Central Asia",
  "Pakistan": "South and Central Asia",
  "Sri Lanka": "South and Central Asia",
  "Tajikistan": "South and Central Asia",
  "Turkmenistan": "South and Central Asia",
  "Uzbekistan": "South and Central Asia",
  "Antigua and Barbuda": "Western Hemisphere",
  "Argentina": "Western Hemisphere",
  "Bahamas": "Western Hemisphere",
  "Barbados": "Western Hemisphere",
  "Belize": "Western Hemisphere",
  "Bolivia": "Western Hemisphere",
  "Brazil": "Western Hemisphere",
  "Canada": "Western Hemisphere",
  "Chile": "Western Hemisphere",
  "Colombia": "Western Hemisphere",
  "Costa Rica": "Western Hemisphere",
  "Cuba": "Western Hemisphere",
  "Dominica": "Western Hemisphere",
  "Dominican Republic": "Western Hemisphere",
  "Ecuador": "Western Hemisphere",
  "El Salvador": "Western Hemisphere",
  "Grenada": "Western Hemisphere",
  "Guatemala": "Western Hemisphere",
  "Guyana": "Western Hemisphere",
  "Haiti": "Western Hemisphere",
  "Honduras": "Western Hemisphere",
  "Jamaica": "Western Hemisphere",
  "Mexico": "Western Hemisphere",
  "Nicaragua": "Western Hemisphere",
  "Panama": "Western Hemisphere",
  "Paraguay": "Western Hemisphere",
  "Peru": "Western Hemisphere",
  "Saint Kitts and Nevis": "Western Hemisphere",
  "Saint Lucia": "Western Hemisphere",
  "Saint Vincent and the Grenadines": "Western Hemisphere",
  "Suriname": "Western Hemisphere",
  "Trinadad and Tobago": "Western Hemisphere",
  "Uruguay": "Western Hemisphere",
  "Venezuela": "Western Hemisphere"
};

// find DoS region by iso
var ISOs = {
  "AGO": "Africa",
  "BEN": "Africa",
  "BWA": "Africa",
  "BFA": "Africa",
  "BDI": "Africa",
  "CPV": "Africa",
  "CMR": "Africa",
  "CAF": "Africa",
  "TCD": "Africa",
  "COM": "Africa",
  "CIV": "Africa",
  "COD": "Africa",
  "DJI": "Africa",
  "GNQ": "Africa",
  "ERI": "Africa",
  "SWZ": "Africa",
  "ETH": "Africa",
  "GAB": "Africa",
  "GMB": "Africa",
  "GHA": "Africa",
  "GIN": "Africa",
  "GNB": "Africa",
  "KEN": "Africa",
  "LSO": "Africa",
  "LBR": "Africa",
  "MDG": "Africa",
  "MWI": "Africa",
  "MLI": "Africa",
  "MRT": "Africa",
  "MUS": "Africa",
  "MOZ": "Africa",
  "NAM": "Africa",
  "NER": "Africa",
  "NGA": "Africa",
  "COG": "Africa",
  "RWA": "Africa",
  "STP": "Africa",
  "SEN": "Africa",
  "SYC": "Africa",
  "SLE": "Africa",
  "SOM": "Africa",
  "ZAF": "Africa",
  "SSD": "Africa",
  "SDN": "Africa",
  "TZA": "Africa",
  "TGO": "Africa",
  "UGA": "Africa",
  "ZMB": "Africa",
  "ZWE": "Africa",
  "AUS": "East Asia and Pacific",
  "BRN": "East Asia and Pacific",
  "MMR": "East Asia and Pacific",
  "KHM": "East Asia and Pacific",
  "CHN": "East Asia and Pacific",
  "FJI": "East Asia and Pacific",
  "IDN": "East Asia and Pacific",
  "JPN": "East Asia and Pacific",
  "KIR": "East Asia and Pacific",
  "LAO": "East Asia and Pacific",
  "MYS": "East Asia and Pacific",
  "MHL": "East Asia and Pacific",
  "FSM": "East Asia and Pacific",
  "MNG": "East Asia and Pacific",
  "NRU": "East Asia and Pacific",
  "NZL": "East Asia and Pacific",
  "PRK": "East Asia and Pacific",
  "PLW": "East Asia and Pacific",
  "PNG": "East Asia and Pacific",
  "PHL": "East Asia and Pacific",
  "WSM": "East Asia and Pacific",
  "SGP": "East Asia and Pacific",
  "SLB": "East Asia and Pacific",
  "KOR": "East Asia and Pacific",
  "TWN": "East Asia and Pacific",
  "THA": "East Asia and Pacific",
  "TLS": "East Asia and Pacific",
  "TON": "East Asia and Pacific",
  "TUV": "East Asia and Pacific",
  "VUT": "East Asia and Pacific",
  "VNM": "East Asia and Pacific",
  "ALB": "Europe and Eurasia",
  "AND": "Europe and Eurasia",
  "ARM": "Europe and Eurasia",
  "AUT": "Europe and Eurasia",
  "AZE": "Europe and Eurasia",
  "BLR": "Europe and Eurasia",
  "BEL": "Europe and Eurasia",
  "BIH": "Europe and Eurasia",
  "BGR": "Europe and Eurasia",
  "HRV": "Europe and Eurasia",
  "CYP": "Europe and Eurasia",
  "CZE": "Europe and Eurasia",
  "DNK": "Europe and Eurasia",
  "EST": "Europe and Eurasia",
  "FIN": "Europe and Eurasia",
  "FRA": "Europe and Eurasia",
  "GEO": "Europe and Eurasia",
  "DEU": "Europe and Eurasia",
  "GRC": "Europe and Eurasia",
  "GRL": "Europe and Eurasia",
  "VAT": "Europe and Eurasia",
  "HUN": "Europe and Eurasia",
  "ISL": "Europe and Eurasia",
  "IRL": "Europe and Eurasia",
  "ITA": "Europe and Eurasia",
  "RKS": "Europe and Eurasia",
  "LVA": "Europe and Eurasia",
  "LIE": "Europe and Eurasia",
  "LTU": "Europe and Eurasia",
  "LUX": "Europe and Eurasia",
  "MLT": "Europe and Eurasia",
  "MDA": "Europe and Eurasia",
  "MCO": "Europe and Eurasia",
  "MNE": "Europe and Eurasia",
  "NLD": "Europe and Eurasia",
  "MKD": "Europe and Eurasia",
  "NOR": "Europe and Eurasia",
  "POL": "Europe and Eurasia",
  "PRT": "Europe and Eurasia",
  "ROU": "Europe and Eurasia",
  "RUS": "Europe and Eurasia",
  "SMR": "Europe and Eurasia",
  "SRB": "Europe and Eurasia",
  "SVK": "Europe and Eurasia",
  "SVN": "Europe and Eurasia",
  "ESP": "Europe and Eurasia",
  "SWE": "Europe and Eurasia",
  "CHE": "Europe and Eurasia",
  "TUR": "Europe and Eurasia",
  "UKR": "Europe and Eurasia",
  "GBR": "Europe and Eurasia",
  "DZA": "Near East",
  "BHR": "Near East",
  "EGY": "Near East",
  "IRN": "Near East",
  "IRQ": "Near East",
  "ISR": "Near East",
  "JOR": "Near East",
  "KWT": "Near East",
  "LBN": "Near East",
  "LBY": "Near East",
  "MAR": "Near East",
  "OMN": "Near East",
  "PSE": "Near East",
  "QAT": "Near East",
  "SAU": "Near East",
  "SYR": "Near East",
  "TUN": "Near East",
  "ARE": "Near East",
  "YEM": "Near East",
  "AFG": "South and Central Asia",
  "BGD": "South and Central Asia",
  "BTN": "South and Central Asia",
  "IND": "South and Central Asia",
  "KAZ": "South and Central Asia",
  "KGZ": "South and Central Asia",
  "MDV": "South and Central Asia",
  "NPL": "South and Central Asia",
  "PAK": "South and Central Asia",
  "LKA": "South and Central Asia",
  "TJK": "South and Central Asia",
  "TKM": "South and Central Asia",
  "UZB": "South and Central Asia",
  "ATG": "Western Hemisphere",
  "ARG": "Western Hemisphere",
  "BHS": "Western Hemisphere",
  "BRB": "Western Hemisphere",
  "BLZ": "Western Hemisphere",
  "BOL": "Western Hemisphere",
  "BRA": "Western Hemisphere",
  "CAN": "Western Hemisphere",
  "CHL": "Western Hemisphere",
  "COL": "Western Hemisphere",
  "CRI": "Western Hemisphere",
  "CUB": "Western Hemisphere",
  "DMA": "Western Hemisphere",
  "DOM": "Western Hemisphere",
  "ECU": "Western Hemisphere",
  "SLV": "Western Hemisphere",
  "GRD": "Western Hemisphere",
  "GTM": "Western Hemisphere",
  "GUY": "Western Hemisphere",
  "HTI": "Western Hemisphere",
  "HND": "Western Hemisphere",
  "JAM": "Western Hemisphere",
  "MEX": "Western Hemisphere",
  "NIC": "Western Hemisphere",
  "PAN": "Western Hemisphere",
  "PRY": "Western Hemisphere",
  "PER": "Western Hemisphere",
  "KNA": "Western Hemisphere",
  "LCA": "Western Hemisphere",
  "VCT": "Western Hemisphere",
  "SUR": "Western Hemisphere",
  "TTO": "Western Hemisphere",
  "URY": "Western Hemisphere",
  "VEN": "Western Hemisphere"
};

// region iso 3 arrays
var AfricaISOs = ["AGO", "BEN", "BWA", "BFA", "BDI", "CPV", "CMR", "CAF", "TCD", "COM", "CIV", "COD", "DJI", "GNQ", "ERI", "SWZ", "ETH", "GAB", "GMB", "GHA", "GIN", "GNB", "KEN", "LSO", "LBR", "MDG", "MWI", "MLI", "MRT", "MUS", "MOZ", "NAM", "NER", "NGA", "COG", "RWA", "STP", "SEN", "SYC", "SLE", "SOM", "ZAF", "SSD", "SDN", "TZA", "TGO", "UGA", "ZMB", "ZWE"];
var EastAsiaAndPacificISOs = ["AUS", "BRN", "MMR", "KHM", "CHN", "FJI", "IDN", "JPN", "KIR", "LAO", "MYS", "MHL", "FSM", "MNG", "NRU", "NZL", "PRK", "PLW", "PNG", "PHL", "WSM", "SGP", "SLB", "KOR", "TWN", "THA", "TLS", "TON", "TUV", "VUT", "VNM"];
var EuropeAndEurasiaISOs = ["ALB", "AND", "ARM", "AUT", "AZE", "BLR", "BEL", "BIH", "BGR", "HRV", "CYP", "CZE", "DNK", "EST", "FIN", "FRA", "GEO", "GRL", "DEU", "GRC", "VAT", "HUN", "ISL", "IRL", "ITA", "RKS", "LVA", "LIE", "LTU", "LUX", "MLT", "MDA", "MCO", "MNE", "NLD", "MKD", "NOR", "POL", "PRT", "ROU", "RUS", "SMR", "SRB", "SVK", "SVN", "ESP", "SWE", "CHE", "TUR", "UKR", "GBR"];
var NearEastISOs = ["DZA", "BHR", "EGY", "IRN", "IRQ", "ISR", "JOR", "KWT", "LBN", "LBY", "MAR", "OMN", "PSE", "QAT", "SAU", "SYR", "TUN", "ARE", "YEM"];
var SouthAndCentralAsiaISOs = ["AFG", "BGD", "BTN", "IND", "KAZ", "KGZ", "MDV", "NPL", "PAK", "LKA", "TJK", "TKM", "UZB"];
var WesternHemisphereISOs = [ "ATG", "ARG", "BHS", "BRB", "BLZ", "BOL", "BRA", "CAN", "CHL", "COL", "CRI", "CUB", "DMA", "DOM", "ECU", "SLV", "GRD", "GTM", "GUY", "HTI", "HND", "JAM", "MEX", "NIC", "PAN", "PRY", "PER", "KNA", "LCA", "VCT", "SUR", "TTO", "URY", "VEN"];
